!pip3 install torch

In [2]:
import torch

In [13]:
v = torch.tensor([1,2,3,4,5,6])
print(v.dtype)
print(v)

torch.int64
tensor([1, 2, 3, 4, 5, 6])


In [14]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())
print(f.dtype)
print(f)

torch.Size([6])
torch.float32
tensor([1., 2., 3., 4., 5., 6.])


In [16]:
# view permette di indicare il formato del tensore, in questo caso una matrice 6 X 1 (6 righe per 1 colonna).
# la poszione dell'indice indica il livello di organizzazione degli elementi.
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [17]:
# possiamo omettere l'ultimo indice, view si occupera di identificare
# automaticamente l'indice necessario per distribuire gli elementi
# in base agli indici precedenti
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])