!pip3 install torch

In [ ]:
import torch
import numpy as np

In [ ]:
v = torch.tensor([1,2,3,4,5,6])
print(v.dtype)
print(v)

torch.int64
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())
print(f.dtype)
print(f)

torch.Size([6])
torch.float32
tensor([1., 2., 3., 4., 5., 6.])


In [ ]:
# view permette di indicare il formato del tensore, in questo caso una matrice 6 X 1 (6 righe per 1 colonna).
# la poszione dell'indice indica il livello di organizzazione degli elementi.
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
# possiamo omettere l'ultimo indice, view si occupera di identificare
# automaticamente l'indice necessario per distribuire gli elementi
# in base agli indici precedenti
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a = np.array([1,2,3,4,5,6])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv.type())
print(tensor_cnv)

torch.LongTensor
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
numpy_cnv = tensor_cnv.numpy
print(numpy_cnv)

<built-in method numpy of Tensor object at 0x7fddd73bae00>
