In [1]:
!pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import torch

In [7]:
# equivalente di range per tensor
one_d = torch.arange(0, 9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
two_d = one_d.view(3, 3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
two_d.dim()

2

In [12]:
two_d[1,2]

tensor(5)

In [16]:
x = torch.arange(0,18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [21]:
x[1,:,1]

tensor([ 7, 10])

Matrix Moltiplication

In [24]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,-1)
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,-1)

In [25]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [26]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])